INSERT INTO users
            (login,
             name,
             email,
             crypted_password,
             salt,
             scm_accounts,
             active,
             external_identity,
             external_identity_provider,
             user_local,
             is_root,
             onboarded)
VALUES     ( ${login},
             ${username},
             ${email},
             ${cryptedPassword},
             ${salt},
             ${scmAccounts},
             true,
             ${username},
             'mpy-ide-server',
             false,
             false,
             true )