INSERT INTO rules
            (
                        name,
                        plugin_rule_key,
                        plugin_name,
                        description,
                        priority,
                        template_id,
                        status,
                        language,
                        is_template,
                        description_format,
                        created_at,
                        updated_at,
                        rule_type,
                        plugin_key
            )
            VALUES
            (
                        ${name},
                        ${name},
                        ${pluginName},
                        ${description},
                        ${severity},
                        44,
                        ${status},
                        ${language},
                        false,
                        'MARKDOWN',
                        ${createdAt},
                        ${updatedAt},
                        ${prevention},
                        ${pluginName}
            )
