INSERT INTO rules
            (
                        name,
                        plugin_rule_key,
                        plugin_name,
                        description,
                        priority,
                        template_id,
                        status,
                        language,
                        is_template,
                        description_format,
                        created_at,
                        updated_at,
                        rule_type,
                        plugin_key
            )
            VALUES
            (
                        ${name},
                        ${pluginRuleKey},
                        ${pluginName},
                        ${description},
                        ${priority},
                        ${templateId},
                        ${status},
                        ${language},
                        ${isTemplate},
                        ${descriptionFormat},
                        ${createdAt},
                        ${updatedAt},
                        ${ruleType},
                        ${pluginKey}
            )
